config/routes.rb
RailsMashUpLive::Application.routes.draw do
  resources :responses

  resources :questions

  resources :courses
	
	match "/questions/by_course_id/:course_id" => "questions#by_course_id"
	match "/responses/by_question_id/:question_id" => "responses#by_question_id"
	
	root :to => "Courses#index"
	
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :course
	
	validates_presence_of :title, :body, :course_id
	
	has_many :responses

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.xml 
	
	skip_before_filter :verify_authenticity_token
	respond_to :json

	before_filter :course_init, :except => [:by_course_id, :create, :destroy]
	def course_init
		@course ||= current_course
	end

#  def index
#    @questions = Question.all

#    respond_to do |format|
#      format.html # index.html.erb
#      format.xml  { render :xml => @questions }
#      format.json { render :json => @questions }
#    end
#  end

  # GET /questions/1
  # GET /questions/1.xml
  def show
    @question = Question.find(params[:id])
    session[:question_id] = @question.id
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @question }
      format.json { render :json => @question}
    end
  end

	def by_course_id
		questions = Course.find(params[:course_id]).questions
		
		respond_to do |format|
			format.json { render :json => questions }
		end
	end

  # GET /questions/new
  # GET /questions/new.xml
  def new
  	@question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @question }
      format.json { render :json => @question}
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # edit.html.erb
      format.xml  { render :xml => @question }
      format.json { render :json => @question}
    end
  end

  # POST /questions
  # POST /questions.xml
  def create
		if params[:question]==nil
			cid = params[:course_id]
			tit = params[:title]
			bod = params[:body]
			@question = Question.new(:course_id => cid, :title => tit, :body => bod)
		else
	    @question = Question.new(params[:question])
			@course = course_init
			@question.course_id = @course.id
		end
		
    respond_to do |format|
      if @question.save
        format.html { redirect_to(@question, :notice => 'Question was successfully created.') }
        format.xml  { render :xml => @question, :status => :created, :location => @question }
        format.json  { render :json => @question, :status => :created, :location => @question }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
        format.json  { render :json => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.xml
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to(@question, :notice => 'Question was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @question.errors, :status => :unprocessable_entity }
				format.json  { render :json => @question.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.xml
  def destroy
    @question = Question.find(params[:id])
    Response.find_all_by_question_id(@question.id).each do |response| 
  		response.destroy
		end
    @question.destroy
    if session[:question_id] != nil
    	session[:question_id] = nil
  	end

    respond_to do |format|
      format.html { redirect_to(current_course) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<h2> Create a question for <%= @course.title %> </h2>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Back', @question %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Course</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.title %></td>
    <td><%= question.body %></td>
    <td><%= question.course_id %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', @course %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @question.title %> </h2>
<p>
  <%= @question.body %>
</p>

<% if not @question.responses.empty? %>
	<h3> Responses: </h3>
	<div class="responses">
		<% @question.responses.each do |response| %>
			<%= response.body %> <br />
			<%= link_to 'Edit', edit_response_path(response) %>
			<br /> <br />
		<% end %>
	</div>
<% else %>
	<p> There are no responses to this question </p>
<% end %>

<%= link_to 'Respond to this Question', new_response_path %> <br />


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Destroy', @question,
	 :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', course_path(@course) %>