config/routes.rb
RailsMashUpLive::Application.routes.draw do
  resources :responses

  resources :questions

  resources :courses
	
	match "/questions/by_course_id/:course_id" => "questions#by_course_id"
	match "/responses/by_question_id/:question_id" => "responses#by_question_id"
	
	root :to => "Courses#index"
	
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.xml
  skip_before_filter :verify_authenticity_token
  respond_to :json
  
#  def index
#    @responses = Response.all

#    respond_to do |format|
#      format.html # index.html.erb
#      format.xml  { render :xml => @responses }
#    end
#  end

  # GET /responses/1
  # GET /responses/1.xml
	before_filter :question_init, :except => [:by_question_id, :create, :destroy] 
  def question_init
  	@question ||= current_question
	end
  
  def show
    @response = Response.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @response }
      format.json { render :json => @response }
    end
  end

  # GET /responses/new
  # GET /responses/new.xml
  def new
    @response = Response.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @response }
      format.json { render :json => @response }
    end
  end
  
	def by_question_id
		responses = Question.find(params[:question_id]).responses
		
		respond_to do |format|
			format.json { render :json => responses }
		end
	end
	
  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
    respond_to do |format|
      format.html # edit.html.erb
      format.xml  { render :xml => @response }
      format.json { render :json => @response }
    end
  end

  # POST /responses
  # POST /responses.xml
  def create
  	if params[:response]==nil
  		qid = params[:question_id]
  		bod = params[:body]
	    @response = Response.new(:question_id => qid, :body => bod)
    else
    	@response = Response.new(params[:response])
    	@question = question_init
    	@response.question_id = @question.id
  	end
		
    respond_to do |format|
      if @response.save
        format.html { redirect_to(@question, :notice => 'Response was successfully created.') }
        format.xml  { render :xml => @response, :status => :created, :location => @response }
        format.json  { render :json => @response, :status => :created, :location => @response }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
        format.json  { render :json => @response.errors, :status => :unprocessable_entity }
      end
    end
  end

#	def mobile_create
#    @response = Response.new(params[:response])
#		
#    respond_to do |format|
#      if @response.save
#        format.xml  { render :xml => @response, :status => :created, :location => @response }
#        format.json  { render :json => @response, :status => :created, :location => @response }
#      else
#        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
#        format.json  { render :json => @response.errors, :status => :unprocessable_entity }
#      end
#    end
#  end

  # PUT /responses/1
  # PUT /responses/1.xml
  def update
    @response = Response.find(params[:id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to(@question, :notice => 'Response was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
        format.json  { render :json => @response.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.xml
  def destroy
		@response = Response.find(params[:id])
    @response.destroy
    
    respond_to do |format|
      format.html { redirect_to(question_init) }
      format.xml  { head :ok }
			format.json  { head :ok }
    end
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 6 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

<%= link_to 'Back', @question %> | 
<%= link_to 'Destroy', @response, 
			:confirm => 'Are you sure?', :method => :delete %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>Qid</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.qid %></td>
    <td><%= response.body %></td>
    <td><%= link_to 'Show', response %></td>
    <td><%= link_to 'Edit', edit_response_path(response) %></td>
    <td><%= link_to 'Destroy', response, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<h1>New response</h1>

<%= render 'form' %>

<%= link_to 'Back', @question %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Qid:</b>
  <%= @response.qid %>
</p>

<p>
  <b>Body:</b>
  <%= @response.body %>
</p>


<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>