config/routes.rb
RailsMashUpLive::Application.routes.draw do
  resources :responses

  resources :questions

  resources :courses
	
	match "/questions/by_course_id/:course_id" => "questions#by_course_id"
	match "/responses/by_question_id/:question_id" => "responses#by_question_id"
	
	root :to => "Courses#index"
	
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
	skip_before_filter :verify_authenticity_token
	respond_to :json
	
  def index
    @courses = Course.all
    session[:course_id] = nil

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
      format.json { render :json => @courses }
    end
  end
	
  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id])
		session[:course_id] = @course.id
		@questions = @course.questions
		
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
      format.json { render :json => [@course, @questions] }
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
      format.json { render :json => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
    
    respond_to do |format| 
    	format.html # edit.html.erb
    	format.xml { render :xml => @course }
    	format.json { render :json => @course }
  	end
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])
		
    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => 'Course was successfully created.') }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
	      format.json { render :json => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
	      format.json { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(@course, :notice => 'Course was successfully updated.') }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
        format.json  { render :json => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    session[:course_id] = nil

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :professor %><br />
    <%= f.text_field :professor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h2>Courses:</h2>

<table class="classlist">
  <tr>
    <th>Title</th>
    <th>Professor</th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= link_to course.title, course %></td>
    <td><%= course.professor %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<h2> <%= @course.title %> </h2>
  <b>Professor:</b>
  <%= @course.professor %>
</p>

<% if not @course.questions.empty? %>
	<b> Questions: </b> <br />
	<% @course.questions.each do |question| %>
		<%= link_to question.title, question %> <br />
	<% end %>
	<br />
<% else %>
	<p> There are no questions for this class. </p>
<% end %>

<%= link_to 'Make a new Question', new_question_path %> <br />

<%= link_to 'Edit', edit_course_path(@course) %> | 
<%= link_to 'Destroy', @course,
			:confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', courses_path %>